package com.nativenavj.domain;

/**
 * Intermediate control targets generated by the Computer.
 * Represents the desired physical orientation and power.
 */
public record Target(
        double roll,
        double pitch,
        double yaw,
        double throttle) {

    public double getRoll() {
        return roll;
    }

    public double getPitch() {
        return pitch;
    }

    public double getYaw() {
        return yaw;
    }

    public double getThrottle() {
        return throttle;
    }

    public static final Target DEFAULT = new Target(0.0, 0.0, 0.0, 0.0);

    /**
     * Creates a neutral/default target.
     */
    public static Target neutral() {
        return DEFAULT;
    }
}
