package com.nativenavj.domain;

/**
 * Intermediate targets generated by Computer for Controllers.
 */
public record Target(
        double roll,
        double pitch,
        double yaw,
        double power) {

    public static Target neutral() {
        return new Target(0, 0, 0, 0.5);
    }
}
